---
title: "DiabeticPreedictionInWomen"
author: "Prateek Nayan"
date: "4/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
__Load required packages:__
```{r loadpackages, include = FALSE}
if(!require("pacman")) install.packages("pacman")
pacman::p_load(e1071, ggplot2,caret,rmarkdown,corrplot,gains,Amelia,tinytex,klar,rpart,rpart.plot,pROC)
```

```{r Load data}
diabetes.df<- read.csv("diabetes.csv") 
str(diabetes.df) 
```

```{r Change the datatype to numeric }
diabetes.df$pregnant = as.numeric(diabetes.df$Pregnancies) 
diabetes.df$glucose = as.numeric(diabetes.df$Glucose) 
diabetes.df$BloodPressure = as.numeric(diabetes.df$BloodPressure) 
diabetes.df$SkinThickness = as.numeric(diabetes.df$SkinThickness) 
diabetes.df$insulin = as.numeric(diabetes.df$Insulin) 
diabetes.df$age = as.numeric(diabetes.df$Age) 
str(diabetes.df) 
```

```{r Heatmap}
install.packages("gplots") #Install package before running heatmap
library(gplots) 

heatmap.2(cor(diabetes.df[, -9]), Rowv = FALSE, Colv = FALSE, dendrogram = "none",           
          cellnote = round(cor(diabetes.df[,-9]),2),           
          notecol = "black", key = FALSE, trace = "none" , margins = c(10,10))
```

```{r Do PCA with non normalized data}
pca <- prcomp( diabetes.df[,-9]) 
summary(pca) 
```

```{r Do PCA with normalized data}
pcanorm<- prcomp(diabetes.df[,-9], scale. = T) 
summary(pcanorm) 
```

```{r Data partitioning}
set.seed(123) 
train.index<- sample(c(1:dim(diabetes.df)[1]),dim(diabetes.df)[1]*0.6) 
train.df<- diabetes.df[train.index, ] 
 valid.df<- diabetes.df[-train.index, ] 
```

```{r NAIVE BAYES}
#setting the outcome variable as categorical
diabetes.df$Outcome<-factor(diabetes.df$Outcome,levels = c(0,1), labels = c("False","True"))
?factor
#summary of the dataset
str(diabetes.df) 
#head of the data
head(diabetes.df)
#visualize the missing data
missmap(diabetes.df)
#summary of the dataset
summary(diabetes.df)
#data partitioning
#build model
set.seed(123)
train.index<-sample(c(1:dim(diabetes.df)[1]),dim(diabetes.df)[1]*0.6)
train.df<-diabetes.df[train.index,]
valid.df<-diabetes.df[-train.index,]
#check dimension of the split
prop.table(table(train.df$Outcome))
prop.table(table(valid.df$Outcome))
#create objects x which holds the predictor variables and y which holds the response variables
x = train.df[,-9]
y = train.df$Outcome
#Naive Bayes
model = train(x,y,'nb',trControl=trainControl(method='cv',number=10))
#Model Evaluation
#Predict testing set
Predict <- predict(model,newdata = valid.df )
#Get the confusion matrix to see accuracy value and other parameter values
confusionMatrix(Predict, valid.df$Outcome )
#checking the importance of the variables
imp<- varImp(model)
plot(imp)
```

```{r lOGISTIC REGRESSION}
# partition with random sample
set.seed(1)
dim(diabetes.df)
train.index<-sample(c(1:dim(diabetes.df)[1]),dim(diabetes.df)[1]*0.6)
train.df<-diabetes.df[train.index,]
valid.df<-diabetes[-train.index,]

# run logistic regression for training data
logit.reg<-glm(Outcome~.,data=train.df,family="binomial")
logit.reg
options(scipen=99)
summary(logit.reg)

# generate confusion matrix for training data
logit.reg.pred.train<-predict(logit.reg,train.df,type = "response")
ifelse(logit.reg.pred.train>0.5,1,0)
confusionMatrix(as.factor(ifelse(logit.reg.pred.train>0.5,1,0)),as.factor(train.df$Outcome))

# run logistic regression for validation data
logit.reg.valid<-glm(Outcome~.,data=valid.df,family="binomial")
logit.reg.valid
options(scipen=99)
summary(logit.reg.valid)

# generate confusion matrix for validation data
logit.reg.pred.valid<-predict(logit.reg.valid,valid.df,type = "response")
ifelse(logit.reg.pred.valid>0.5,1,0)
confusionMatrix(as.factor(ifelse(logit.reg.pred.valid>0.5,1,0)),as.factor(valid.df$Outcome))

#Lift chart for training data
r.train<-roc(train.df$Outcome,logit.reg.pred.train)
plot.roc(r.train)

#Lift chart for validation data
r.valid<-roc(valid.df$Outcome,logit.reg.pred.valid)
plot.roc(r.valid)
```

```{r K-MEANS CLUSTERING}
#Normalising data
diabetes.norm<-sapply(diabetes.df,scale)
#determining kvalue
#elbow method
km_wss <- sapply(1:15, function(k){kmeans(diabetes.norm, k)$tot.withinss})
km_wss
plot(1:15, km_wss, main = "Elbow method",xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")
#Setting k=6
set.seed(123)
km1<-kmeans(diabetes.norm,6)

#Cluster size
km1$size

#Cluster membership
km1$cluster

#Cluster centers
km1$centers

#With-in cluster sum of squares
km1$withinss

#distance between centers
dist(km1$centers)

#Profile plot of centroids
plot(c(0), xaxt = 'n', ylab = "", type = "l", 
     ylim = c(min(km1$centers), max(km1$centers)), xlim = c(0, 8))
axis(1, at = c(1:9), labels = names(diabetes))
for (i in c(1:6))
  lines(km1$centers[i,], lty = i, lwd = 2, col = ifelse(i %in% c(1, 3, 5),
                                                        "black", "dark grey"))
text(x = 0.2, y = km1$centers[, 1], labels = paste("Cluster", c(1:6)))
```

```{r HIERARCHIAL CLUSTERING}
#generating dendogram based on single linkage
d.norm<-dist(diabetes.norm,method='euclidean')
hc1<-hclust(d.norm,method = 'single')
plot(hc1,main="Clustering Dendrogram",ylab="distance")
#setting cluster k=6
memb1<- cutree(hc1,k=6)
memb1
#generating dendogram based on complete linkage
hc2<-hclust(d.norm,method = 'complete')
plot(hc2,main="Clustering Dendrogram",ylab="distance")
#setting cluster k=6
memb2<- cutree(hc2,k=6)
memb2
```

```{r CLASSIFICATION TREES}
#train.df$Outcome<-as.factor(train.df$test) 
default.ct <- rpart(Outcome ~ ., data = train.df, method = "class") 
prp(default.ct, type = 1, extra = 1, under = TRUE,, main="Decision Tree", 
    split.font = 2, varlen = -10, box.palette = blues9) 
default.ct.point.pred <- predict(default.ct,newdata = valid.df,type = "class") 
table(default.ct.point.pred, valid.df$Outcome) 
confusionMatrix(default.ct.point.pred, as.factor(valid.df$Outcome)) 
```



